services:
  - type: web
    name: xdu-partner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u server.py
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
